[package]
name = "fitbit-grabber"
version = "0.1.0"
authors = ["Bradford D. Boyle <bradford.d.boyle@gmail.com>"]

[dependencies]
clap = "2.31"
chrono = "0.4"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
oauth2 = "1.3"
reqwest = "0.8"
tiny_http = "0.6"
tokio-core = "0.1"
url = "1.7"
